package com.lingua_app.backend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

// @Entity tells Hibernate this class maps to a database table.
// @Table(name = "users") explicitly names the table — without it Hibernate would
// default to the class name, which can vary across databases.
@Entity
@Table(name = "users")
// Lombok generates getters and setters for every field, removing boilerplate.
@Getter @Setter
public class User {

    @Id
    // UUID primary keys are generated by the database, not the app, avoiding
    // coordination issues in distributed systems and preventing ID enumeration attacks.
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "uuid") // Ensures PostgreSQL uses the native uuid type
    private UUID id;

    // unique = true adds a database-level UNIQUE constraint (backed by an index in Flyway migration).
    // nullable = false adds a NOT NULL constraint.
    @Column(nullable = false, unique = true, columnDefinition = "citext")
    private String email;

    // Stored as a BCrypt hash — the raw password never persists beyond the request.
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    // updatable = false prevents Hibernate from ever issuing an UPDATE on this column
    // after the initial INSERT, preserving the original creation timestamp.
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    // Soft-delete flag: setting active = false disables the account without losing its data.
    @Column(name = "is_active", nullable = false)
    private boolean active;
}
